<?php
/**
 * @file
 * Icon fonts library definitions.
 */

/**
 * Implements hook_library().
 */
function iconfonts_library() {
  $libraries['spark_icons'] = array(
    'title' => 'Spark icon font library',
    'website' => 'http://drupal.org/project/iconfonts',
    'version' => '1.0',
    'css' => array(
      drupal_get_path('module', 'iconfonts') . '/spark_icons.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}